### ISSUE TITLE
Broken build?

### ISSUE THREAD

**Issue by fengye** [sonnyp/aria2.js#11]
I'm new to node but I wrote a simple test script then it fails when I called open():

```javascript
var Aria2 = require('..')
var aria2Options = {host: 'localhost', port: 6800, secure: false}
var aria2 = new Aria2(aria2Options)

aria2.open();
```

I put the file in the example directory and run `node test.js`. The result is below:
```
events.js:0
(function (exports, require, module, __filename, __dirname) { // Copyright Joy
^
RangeError: Maximum call stack size exceeded
```

However when I use npm package, it seems still has the issue #8 unfixed. 

UPDATE:
If I use the npm package(ver 0.0.6) and manually patched commit https://github.com/sonnyp/aria2.js/commit/ee9a18bac020274606f71fd25f91ab199a693cb6, the script works fine.

My aria2 version is 1.18.8.

**Comment by sonnyp** [comment]
I published version 1.0.0 on npm. Can you please try with that?

**Comment by fengye** [comment]
After npm update, it's the current npm list output:

```
├─┬ aria2@1.0.0
│ ├─┬ httpclient@0.0.4
│ │ └── es6-promise@1.0.0
│ └─┬ ws@0.8.0
│   ├─┬ bufferutil@1.2.1
│   │ ├── bindings@1.2.1
│   │ └── nan@2.0.9
│   ├── options@0.0.6
│   ├── ultron@1.0.2
│   └─┬ utf-8-validate@1.2.1
│     ├── bindings@1.2.1
│     └── nan@2.0.9
```
With the same script (only change is ```var Aira2 = require('aria2')```), it's still the same output:
```
events.js:0
(function (exports, require, module, __filename, __dirname) { // Copyright Joy
^
```

**Comment by sonnyp** [comment]
what is your node version?

Can you give me the complete error?

**Comment by fengye** [comment]
The complete error message is:
```
events.js:0
(function (exports, require, module, __filename, __dirname) { // Copyright Joy
^
RangeError: Maximum call stack size exceeded
```
node --version gives:
```
v0.10.37
```
Guess it's not the latest version, but follow the installation it gives something like:
```
## Confirming "precise" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_4.x/dists/precise/Release'

## Your distribution, identified as "precise", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```
My linux is Ubuntu 12.04, so might be the version issue?

**Comment by sonnyp** [comment]
no no the version is fine

**Comment by sonnyp** [comment]
@fengye how do you start ari2c?

**Comment by fengye** [comment]
I think it's rpc enabled, I greped the ps output:
```
ps -ef|grep aria2
```
which gives:
```
feng_ye   9625 14586  0 23:39 pts/1    00:00:00 grep --color=auto aria2
feng_ye  18899     1  3 Mar12 ?        7-12:27:41 aria2c --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all
```

**Comment by sonnyp** [comment]
reproduced :) gonna send a fix

**Comment by sonnyp** [comment]
Okay, please install new version 1.0.1 and try again, should be fixed now; sorry

**Comment by fengye** [comment]
Great! It works now. Thanks for the quick fix.

However the aria2.send() method seems broken. I'll start another issue.

**Comment by sonnyp** [comment]
@fengye yes please do, I made changes a while ago and broke some stuff, I hope to fix them all.
